import { useState } from 'react';
import { motion } from 'framer-motion';
import { Upload, Info } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../../../components/common';
import s from '../_shared.module.css';
import styles from './AddRole.module.css';

const MODULES = [
  { name: 'UPI', access: true, view: true, create: true, edit: true, approve: false, download: false },
  { name: 'IMPS', access: true, view: true, create: false, edit: false, approve: false, download: false },
  { name: 'NEFT', access: true, view: true, create: true, edit: false, approve: false, download: true },
  { name: 'RTGS', access: false, view: false, create: false, edit: false, approve: false, download: false },
  { name: 'Report', access: true, view: true, create: false, edit: false, approve: false, download: true },
  { name: 'Admin', access: false, view: false, create: false, edit: false, approve: false, download: false },
  { name: 'Setup', access: false, view: false, create: false, edit: false, approve: false, download: false },
  { name: 'Process', access: true, view: true, create: true, edit: true, approve: true, download: true },
  { name: 'Dispute', access: false, view: false, create: false, edit: false, approve: false, download: false },
  { name: 'Reconciliation', access: true, view: true, create: false, edit: false, approve: false, download: true },
];

const PERM_COLS = ['access', 'view', 'create', 'edit', 'approve', 'download'];
const COL_COLORS = { access: 'var(--color-primary-500)', view: 'var(--color-info-500)', create: 'var(--color-success-500)', edit: '#92400e', approve: '#7B3F9E', download: 'var(--color-neutral-500)' };

const AddRole = () => {
  const navigate = useNavigate();
  const [perms, setPerms] = useState(MODULES.map(m => ({ ...m })));
  const [roleName, setRoleName] = useState('');
  const [roleType, setRoleType] = useState('');
  const [status, setStatus] = useState('Active');
  const [description, setDescription] = useState('');
  const [validFrom, setValidFrom] = useState('');
  const [validTo, setValidTo] = useState('');
  const [showImport, setShowImport] = useState(false);

  const togglePerm = (idx, col) => {
    setPerms(prev => prev.map((p, i) => i === idx ? { ...p, [col]: !p[col] } : p));
  };

  const handleSubmit = () => navigate('/new-config/role-approval-sent');

  return (
    <div className={s.page}>
      <PageHeader title="Add New Role" description="Define permissions and module access for this role">
        <button className={`${s.btn} ${s.btnOutline}`} onClick={() => navigate('/new-config/role-list')}>Cancel</button>
        <button className={`${s.btn} ${s.btnOutline}`}>Save as Draft</button>
        <button className={`${s.btn} ${s.btnGold} ${s.btnLg}`} onClick={handleSubmit}>
          Submit for Approval →
        </button>
      </PageHeader>

      {/* Import strip */}
      <div className={styles.importStrip}>
        <Upload size={20} color="var(--color-info-500)" />
        <div className={styles.importTxt}>
          <strong>Auto-populate from file</strong>
          <span>Upload a CSV, Excel, or XML file — fields will be read and filled automatically</span>
        </div>
        <button className={`${s.btn} ${s.btnTeal}`} onClick={() => setShowImport(true)}>
          <Upload size={13} /> Import from File
        </button>
      </div>

      {/* Section 1: Role Details */}
      <motion.div className={s.card} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3 }}>
        <div className={s.cardHead}>
          <span className={s.cardHeadNum}>1</span>
          <span className={s.cardTitle}>Role Details</span>
          <span className={s.cardSub}>(M) = Mandatory &nbsp;·&nbsp; (O) = Optional</span>
        </div>
        <div className={s.cardBody}>
          <div className={`${s.g2} ${styles.formGrid}`}>
            <div className={s.fld}>
              <label>Role Name <span className={s.req}>*</span></label>
              <input className={s.fldInput} type="text" placeholder="e.g. UPI Maker" value={roleName} onChange={e => setRoleName(e.target.value)} />
            </div>
            <div className={s.fld}>
              <label>Role Code</label>
              <input className={`${s.fldInput} ${s.fldRo} ${s.mono}`} type="text" value="ROLE-0041" readOnly />
              <div className={s.hint}>Auto-generated by system</div>
            </div>
            <div className={s.fld}>
              <label>Role Type <span className={s.req}>*</span></label>
              <select className={s.fldSelect} value={roleType} onChange={e => setRoleType(e.target.value)}>
                <option value="">Select type…</option>
                <option>Internal</option><option>External</option>
              </select>
            </div>
            <div className={s.fld}>
              <label>Status <span className={s.req}>*</span></label>
              <select className={s.fldSelect} value={status} onChange={e => setStatus(e.target.value)}>
                <option>Active</option><option>Inactive</option>
              </select>
            </div>
            <div className={`${s.fld}`} style={{ gridColumn: '1 / -1' }}>
              <label>Description (O)</label>
              <textarea className={s.fldTextarea} placeholder="Brief description of this role's purpose…" value={description} onChange={e => setDescription(e.target.value)} />
            </div>
          </div>
        </div>
      </motion.div>

      {/* Section 2: Validity */}
      <motion.div className={s.card} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08, duration: 0.3 }}>
        <div className={s.cardHead}>
          <span className={s.cardHeadNum}>2</span>
          <span className={s.cardTitle}>Validity Period</span>
        </div>
        <div className={s.cardBody}>
          <div className={s.g2}>
            <div className={s.fld}>
              <label>Valid From <span className={s.req}>*</span></label>
              <input className={s.fldInput} type="date" value={validFrom} onChange={e => setValidFrom(e.target.value)} />
            </div>
            <div className={s.fld}>
              <label>Valid To</label>
              <input className={s.fldInput} type="date" value={validTo} onChange={e => setValidTo(e.target.value)} />
              <div className={s.hint}>Leave blank for no expiry</div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Section 3: Permission Matrix */}
      <motion.div className={s.card} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15, duration: 0.3 }}>
        <div className={s.cardHead}>
          <span className={s.cardHeadNum}>3</span>
          <span className={s.cardTitle}>Module Permission Matrix</span>
          <span className={s.cardSub}>Select what each module allows this role to do</span>
        </div>
        <div className={`${s.cardBody}`} style={{ padding: 0 }}>
          <div className={s.infoBox + ' ' + s.infoBlue} style={{ margin: 'var(--space-4)', marginBottom: 0 }}>
            <Info size={14} /><span>Access must be enabled before other permissions become available. Disabled rows indicate restricted modules.</span>
          </div>
          <div style={{ overflowX: 'auto', margin: 'var(--space-4) 0 0' }}>
            <table className={styles.permTable}>
              <thead>
                <tr>
                  <th style={{ textAlign: 'left', width: 160 }}>Module</th>
                  {PERM_COLS.map(col => (
                    <th key={col} style={{ color: COL_COLORS[col] }}>{col.charAt(0).toUpperCase() + col.slice(1)}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {perms.map((p, idx) => (
                  <tr key={p.name} className={!p.access ? styles.rowDisabled : ''}>
                    <td style={{ textAlign: 'left', fontWeight: 'var(--font-medium)' }}>{p.name}</td>
                    {PERM_COLS.map(col => (
                      <td key={col}>
                        <input
                          type="checkbox"
                          className={styles.permCb}
                          checked={p[col]}
                          disabled={col !== 'access' && !p.access}
                          onChange={() => togglePerm(idx, col)}
                        />
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className={styles.legend}>
            {PERM_COLS.map(col => (
              <div key={col} className={styles.legItem}>
                <span className={styles.legDot} style={{ background: COL_COLORS[col] }} />
                {col.charAt(0).toUpperCase() + col.slice(1)}
              </div>
            ))}
          </div>
        </div>
      </motion.div>

      <div className={styles.formActions}>
        <button className={`${s.btn} ${s.btnOutline}`} onClick={() => navigate('/new-config/role-list')}>← Cancel</button>
        <div style={{ display: 'flex', gap: 'var(--space-2)' }}>
          <button className={`${s.btn} ${s.btnOutline}`}>Save as Draft</button>
          <button className={`${s.btn} ${s.btnGold} ${s.btnLg}`} onClick={handleSubmit}>Submit for Approval →</button>
        </div>
      </div>

      {/* Import Modal */}
      {showImport && (
        <div className={`${s.overlay} ${s.overlayShow}`} onClick={() => setShowImport(false)}>
          <div className={s.modal} onClick={e => e.stopPropagation()}>
            <div className={s.modalHead}>
              <h3><Upload size={14} color="rgba(255,255,255,0.8)" /> Import Role from File</h3>
              <button className={s.modalClose} onClick={() => setShowImport(false)}>×</button>
            </div>
            <div className={s.modalBody}>
              <div className={s.tmplStrip}>
                <span>Download template to ensure correct column format</span>
                <a>Download Template (CSV)</a>
              </div>
              <div className={s.dropZone}>
                <Upload size={36} color="var(--color-neutral-400)" style={{ margin: '0 auto 12px' }} />
                <h4 style={{ fontSize: 'var(--text-sm)', fontWeight: 'var(--font-semibold)', marginBottom: 4 }}>Drop file here or click to browse</h4>
                <p style={{ fontSize: 'var(--text-xs)', color: 'var(--color-neutral-500)' }}>CSV, XLSX or XML — max 5 MB</p>
              </div>
            </div>
            <div className={s.modalFooter}>
              <button className={`${s.btn} ${s.btnOutline}`} onClick={() => setShowImport(false)}>Cancel</button>
              <button className={`${s.btn} ${s.btnNavy}`}>Import &amp; Fill Fields</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AddRole;
