-- ============================================================
-- Dummy test data for the Role / Menu / User maker-checker flow +
-- Product Capability (Maker/Checker pool) feature.
--
-- PREREQUISITES (run in this exact order if not already done):
--   1. migration_product_capability.sql  (adds Menu SUBMITTED_BY/APPROVED_BY
--      + creates RECON_PRODUCT_CAPABILITY_MAP)
--   2. seed_products.sql                 (UPI, AEPS, etc.)
--   3. This file.
-- If you hit errors partway through, run cleanup_demo_maker_checker.sql
-- first, then re-run this file from the top.
--
-- Auto-links to the FIRST top-level bank found in RECON_BANK_MASTER.
--
-- Covers every status you'll want to eyeball in the UI:
--   Roles:  DRAFT, PENDING, ACTIVE, REJECTED
--   Menus:  DRAFT, PENDING, ACTIVE (Y)
--   Users:  ACTIVE_PENDING (checker queue), ACTIVE
--   Privilege mapping: 1 role -> 2 menus (C_ROLE_MENU_MAP)
--   Product capability: MAKER (delegable), CHECKER, and a sub-Maker
--                        granted BY the first Maker (non-delegable)
-- ============================================================

SET DEFINE OFF;

-- ── ROLES ──────────────────────────────────────────────────────────
INSERT INTO KAL_RECON.RECON_ROLE_MASTER
    (ROLE_CODE, ROLE_NAME, ROLE_TYPE, ROLE_DESC, STATUS, CREATED_BY, CREATED_AT)
VALUES ('DEMO_UPI_MAKER', 'UPI Maker Role', 'INTERNAL', 'Demo role - draft, not yet submitted', 'DRAFT', 'demo.seed', SYSTIMESTAMP);
COMMIT;

INSERT INTO KAL_RECON.RECON_ROLE_MASTER
    (ROLE_CODE, ROLE_NAME, ROLE_TYPE, ROLE_DESC, STATUS, SUBMITTED_BY, CREATED_BY, CREATED_AT)
VALUES ('DEMO_UPI_CHECKER', 'UPI Checker Role', 'INTERNAL', 'Demo role - submitted, awaiting checker', 'PENDING', 'demo.seed', 'demo.seed', SYSTIMESTAMP);
COMMIT;

INSERT INTO KAL_RECON.RECON_ROLE_MASTER
    (ROLE_CODE, ROLE_NAME, ROLE_TYPE, ROLE_DESC, STATUS, SUBMITTED_BY, APPROVED_BY, CREATED_BY, CREATED_AT)
VALUES ('DEMO_TELLER', 'Teller Role', 'INTERNAL', 'Demo role - approved and active', 'ACTIVE', 'demo.seed', 'demo.checker.seed', 'demo.seed', SYSTIMESTAMP);
COMMIT;

INSERT INTO KAL_RECON.RECON_ROLE_MASTER
    (ROLE_CODE, ROLE_NAME, ROLE_TYPE, ROLE_DESC, STATUS, SUBMITTED_BY, CREATED_BY, CREATED_AT)
VALUES ('DEMO_OLD_ROLE', 'Rejected Analyst Role', 'EXTERNAL', 'Demo role - checker rejected this one', 'REJECTED', 'demo.seed', 'demo.seed', SYSTIMESTAMP);
COMMIT;

-- ── MENUS (MENU_ID is sequence-generated — must supply SEQ_MENU.NEXTVAL explicitly
--    since we're inserting via raw SQL, not through Hibernate) ─────────────────
INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_ID, MENU_TYPE, MENU_NAME, DESCRIPTION, SUB_MENU_FLAG, STATUS, CREATED_BY, CREATED_DATE, INSERT_DATE)
VALUES (KAL_RECON.SEQ_MENU.NEXTVAL, 'Master', 'Demo Reports', 'Demo master menu - active', 'N', 'Y', 'demo.seed', SYSTIMESTAMP, SYSTIMESTAMP);
COMMIT;

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_ID, MENU_TYPE, MENU_NAME, DESCRIPTION, MENU_PARENT, SUB_MENU_FLAG, MENU_URL, STATUS, CREATED_BY, CREATED_DATE, INSERT_DATE)
VALUES (KAL_RECON.SEQ_MENU.NEXTVAL, 'Main', 'Demo Draft Report', 'Demo main menu - draft, not submitted', 'Demo Reports', 'N', '/demo/draft-report', 'DRAFT', 'demo.seed', SYSTIMESTAMP, SYSTIMESTAMP);
COMMIT;

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_ID, MENU_TYPE, MENU_NAME, DESCRIPTION, MENU_PARENT, SUB_MENU_FLAG, MENU_URL, STATUS, SUBMITTED_BY, CREATED_BY, CREATED_DATE, INSERT_DATE)
VALUES (KAL_RECON.SEQ_MENU.NEXTVAL, 'Main', 'Demo Pending Report', 'Demo main menu - submitted, awaiting checker', 'Demo Reports', 'N', '/demo/pending-report', 'PENDING', 'demo.seed', 'demo.seed', SYSTIMESTAMP, SYSTIMESTAMP);
COMMIT;

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_ID, MENU_TYPE, MENU_NAME, DESCRIPTION, MENU_PARENT, SUB_MENU_FLAG, MENU_URL, STATUS, SUBMITTED_BY, APPROVED_BY, CREATED_BY, CREATED_DATE, INSERT_DATE)
VALUES (KAL_RECON.SEQ_MENU.NEXTVAL, 'Main', 'Demo Active Report', 'Demo main menu - approved and active', 'Demo Reports', 'N', '/demo/active-report', 'Y', 'demo.seed', 'demo.checker.seed', 'demo.seed', SYSTIMESTAMP, SYSTIMESTAMP);
COMMIT;

-- ── USERS (linked to the first top-level bank) — each its own transaction
--    to avoid ORA-12838 (parallel-modify conflict on RECON_BANK_MASTER) ──
INSERT INTO KAL_RECON.RCN_RECON_USER
    (BANK_ID, USERNAME, FULL_NAME, EMAIL, MOBILE_NUMBER, USER_TYPE, CONTACT_RANK,
     PASSWORD_HASH, PASSWORD_SET, STATUS, APPROVED_YN, EMPLOYMENT_TYPE, CREATED_AT, CREATED_BY)
SELECT BANK_ID, 'demo.maker', 'Demo Maker', 'demo.maker@example.com', '9000000001',
       'BANK_USER', 'PRIMARY', '$2a$10$dummyBcryptHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXX', 1,
       'ACTIVE', 'Y', 'INTERNAL', SYSTIMESTAMP, 'demo.seed'
FROM KAL_RECON.RECON_BANK_MASTER
WHERE PARENT_BANK_ID IS NULL AND CONTACT_RANK = 'PRIMARY' AND ROWNUM = 1;
COMMIT;

INSERT INTO KAL_RECON.RCN_RECON_USER
    (BANK_ID, USERNAME, FULL_NAME, EMAIL, MOBILE_NUMBER, USER_TYPE, CONTACT_RANK,
     PASSWORD_HASH, PASSWORD_SET, STATUS, APPROVED_YN, EMPLOYMENT_TYPE, CREATED_AT, CREATED_BY)
SELECT BANK_ID, 'demo.checker', 'Demo Checker', 'demo.checker@example.com', '9000000002',
       'BANK_USER', 'PRIMARY', '$2a$10$dummyBcryptHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXX', 1,
       'ACTIVE', 'Y', 'INTERNAL', SYSTIMESTAMP, 'demo.seed'
FROM KAL_RECON.RECON_BANK_MASTER
WHERE PARENT_BANK_ID IS NULL AND CONTACT_RANK = 'PRIMARY' AND ROWNUM = 1;
COMMIT;

INSERT INTO KAL_RECON.RCN_RECON_USER
    (BANK_ID, USERNAME, FULL_NAME, EMAIL, MOBILE_NUMBER, USER_TYPE, CONTACT_RANK,
     PASSWORD_HASH, PASSWORD_SET, STATUS, APPROVED_YN, EMPLOYMENT_TYPE, CREATED_AT, CREATED_BY)
SELECT BANK_ID, 'demo.submaker', 'Demo Sub Maker', 'demo.submaker@example.com', '9000000003',
       'BANK_USER', 'PRIMARY', '$2a$10$dummyBcryptHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXX', 1,
       'ACTIVE', 'Y', 'INTERNAL', SYSTIMESTAMP, 'demo.seed'
FROM KAL_RECON.RECON_BANK_MASTER
WHERE PARENT_BANK_ID IS NULL AND CONTACT_RANK = 'PRIMARY' AND ROWNUM = 1;
COMMIT;

INSERT INTO KAL_RECON.RCN_RECON_USER
    (BANK_ID, USERNAME, FULL_NAME, EMAIL, MOBILE_NUMBER, USER_TYPE, CONTACT_RANK,
     PASSWORD_HASH, PASSWORD_SET, STATUS, APPROVED_YN, EMPLOYMENT_TYPE, CREATED_AT, CREATED_BY)
SELECT BANK_ID, 'demo.pendinguser', 'Demo Pending User', 'demo.pendinguser@example.com', '9000000004',
       'BANK_USER', 'PRIMARY', '$2a$10$dummyBcryptHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXX', 1,
       'ACTIVE_PENDING', 'N', 'INTERNAL', SYSTIMESTAMP, 'demo.seed'
FROM KAL_RECON.RECON_BANK_MASTER
WHERE PARENT_BANK_ID IS NULL AND CONTACT_RANK = 'PRIMARY' AND ROWNUM = 1;
COMMIT;

-- ── PRIVILEGE MAPPING — link DEMO_TELLER role to the 2 active/approved demo menus ──
INSERT INTO KAL_RECON.C_ROLE_MENU_MAP (ROLE_ID, MENU_ID, CREATED_AT, CREATED_BY)
SELECT r.ROLE_ID, m.MENU_ID, SYSTIMESTAMP, 'demo.seed'
FROM KAL_RECON.RECON_ROLE_MASTER r, KAL_RECON.RECON_MENU_MASTER m
WHERE r.ROLE_CODE = 'DEMO_TELLER' AND m.MENU_NAME = 'Demo Reports';
COMMIT;

INSERT INTO KAL_RECON.C_ROLE_MENU_MAP (ROLE_ID, MENU_ID, CREATED_AT, CREATED_BY)
SELECT r.ROLE_ID, m.MENU_ID, SYSTIMESTAMP, 'demo.seed'
FROM KAL_RECON.RECON_ROLE_MASTER r, KAL_RECON.RECON_MENU_MASTER m
WHERE r.ROLE_CODE = 'DEMO_TELLER' AND m.MENU_NAME = 'Demo Active Report';
COMMIT;

-- ── PRODUCT CAPABILITY — UPI Maker (delegable) + UPI Checker + a sub-Maker ──
INSERT INTO KAL_RECON.RECON_PRODUCT_CAPABILITY_MAP
    (PRODUCT_ID, USER_ID, CAPABILITY_TYPE, ACTION_TYPE, CAN_DELEGATE, GRANTED_BY, GRANTED_AT, STATUS)
SELECT p.PRODUCT_ID, u.USER_ID, 'MAKER', 'ROLE', 'Y', g.USER_ID, SYSTIMESTAMP, 'ACTIVE'
FROM KAL_RECON.RECON_PRODUCT_MASTER p, KAL_RECON.RCN_RECON_USER u, KAL_RECON.RCN_RECON_USER g
WHERE p.PRODUCT_NAME = 'UPI' AND u.USERNAME = 'demo.maker' AND g.USERNAME = 'demo.checker';
COMMIT;

-- demo.checker: CHECKER on UPI/ROLE (stand-in — in real flow this would be granted
-- by an Admin account, not another Checker; fine for demo purposes)
INSERT INTO KAL_RECON.RECON_PRODUCT_CAPABILITY_MAP
    (PRODUCT_ID, USER_ID, CAPABILITY_TYPE, ACTION_TYPE, CAN_DELEGATE, GRANTED_BY, GRANTED_AT, STATUS)
SELECT p.PRODUCT_ID, u.USER_ID, 'CHECKER', 'ROLE', 'N', u.USER_ID, SYSTIMESTAMP, 'ACTIVE'
FROM KAL_RECON.RECON_PRODUCT_MASTER p, KAL_RECON.RCN_RECON_USER u
WHERE p.PRODUCT_NAME = 'UPI' AND u.USERNAME = 'demo.checker';
COMMIT;

-- demo.submaker: MAKER on UPI/ROLE, non-delegable, granted BY demo.maker (the delegation chain)
INSERT INTO KAL_RECON.RECON_PRODUCT_CAPABILITY_MAP
    (PRODUCT_ID, USER_ID, CAPABILITY_TYPE, ACTION_TYPE, CAN_DELEGATE, GRANTED_BY, GRANTED_AT, STATUS)
SELECT p.PRODUCT_ID, u.USER_ID, 'MAKER', 'ROLE', 'N', g.USER_ID, SYSTIMESTAMP, 'ACTIVE'
FROM KAL_RECON.RECON_PRODUCT_MASTER p, KAL_RECON.RCN_RECON_USER u, KAL_RECON.RCN_RECON_USER g
WHERE p.PRODUCT_NAME = 'UPI' AND u.USERNAME = 'demo.submaker' AND g.USERNAME = 'demo.maker';
COMMIT;

-- demo.maker: MAKER on AEPS/MENU too, delegable, granted by demo.checker (extra product for variety)
INSERT INTO KAL_RECON.RECON_PRODUCT_CAPABILITY_MAP
    (PRODUCT_ID, USER_ID, CAPABILITY_TYPE, ACTION_TYPE, CAN_DELEGATE, GRANTED_BY, GRANTED_AT, STATUS)
SELECT p.PRODUCT_ID, u.USER_ID, 'MAKER', 'MENU', 'Y', g.USER_ID, SYSTIMESTAMP, 'ACTIVE'
FROM KAL_RECON.RECON_PRODUCT_MASTER p, KAL_RECON.RCN_RECON_USER u, KAL_RECON.RCN_RECON_USER g
WHERE p.PRODUCT_NAME = 'AEPS' AND u.USERNAME = 'demo.maker' AND g.USERNAME = 'demo.checker';
COMMIT;

-- Verify:
-- SELECT ROLE_CODE, ROLE_NAME, STATUS, SUBMITTED_BY, APPROVED_BY FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE LIKE 'DEMO_%';
-- SELECT MENU_NAME, MENU_TYPE, STATUS, SUBMITTED_BY, APPROVED_BY FROM KAL_RECON.RECON_MENU_MASTER WHERE MENU_NAME LIKE 'Demo %';
-- SELECT USERNAME, FULL_NAME, STATUS, APPROVED_YN FROM KAL_RECON.RCN_RECON_USER WHERE USERNAME LIKE 'demo.%';
-- SELECT c.PRODUCT_ID, pm.PRODUCT_NAME, c.USER_ID, u.USERNAME, c.CAPABILITY_TYPE, c.ACTION_TYPE, c.CAN_DELEGATE, c.GRANTED_BY, gu.USERNAME AS GRANTED_BY_USERNAME, c.STATUS
--   FROM KAL_RECON.RECON_PRODUCT_CAPABILITY_MAP c
--   JOIN KAL_RECON.RCN_RECON_USER u ON u.USER_ID = c.USER_ID
--   JOIN KAL_RECON.RCN_RECON_USER gu ON gu.USER_ID = c.GRANTED_BY
--   JOIN KAL_RECON.RECON_PRODUCT_MASTER pm ON pm.PRODUCT_ID = c.PRODUCT_ID;
