-- ============================================================
-- Dummy test data: 2 BANK_USER + 2 BRANCH_USER rows in RCN_RECON_USER
-- Auto-links to the FIRST top-level bank and FIRST branch found in
-- RECON_BANK_MASTER — so you don't need to know exact BANK_ID values.
-- Run, then check /bank-admin/my-organization/user-status (BANK_USER)
-- and /branch-admin/my-organization/admin-status or hierarchy (BRANCH_USER).
-- ============================================================

SET DEFINE OFF;

-- ── 2 BANK_USER rows (linked to the first top-level bank) ──
INSERT INTO KAL_RECON.RCN_RECON_USER
    (BANK_ID, USERNAME, FULL_NAME, EMAIL, MOBILE_NUMBER, USER_TYPE, CONTACT_RANK,
     PASSWORD_HASH, PASSWORD_SET, STATUS, APPROVED_YN, EMPLOYMENT_TYPE, CREATED_AT, CREATED_BY)
SELECT BANK_ID, 'test.bankuser1', 'Test Bank User One', 'test.bankuser1@example.com', '9876543210',
       'BANK_USER', 'PRIMARY', '$2a$10$dummyBcryptHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXX', 1,
       'ACTIVE', 'Y', 'INTERNAL', SYSTIMESTAMP, 'SYSTEM'
FROM KAL_RECON.RECON_BANK_MASTER
WHERE PARENT_BANK_ID IS NULL AND CONTACT_RANK = 'PRIMARY' AND ROWNUM = 1;

INSERT INTO KAL_RECON.RCN_RECON_USER
    (BANK_ID, USERNAME, FULL_NAME, EMAIL, MOBILE_NUMBER, USER_TYPE, CONTACT_RANK,
     PASSWORD_HASH, PASSWORD_SET, STATUS, APPROVED_YN, EMPLOYMENT_TYPE, CREATED_AT, CREATED_BY)
SELECT BANK_ID, 'test.bankuser2', 'Test Bank User Two', 'test.bankuser2@example.com', '9876543211',
       'BANK_USER', 'PRIMARY', '$2a$10$dummyBcryptHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXX', 1,
       'ACTIVE', 'Y', 'EXTERNAL', SYSTIMESTAMP, 'SYSTEM'
FROM KAL_RECON.RECON_BANK_MASTER
WHERE PARENT_BANK_ID IS NULL AND CONTACT_RANK = 'PRIMARY' AND ROWNUM = 1;

-- ── 2 BRANCH_USER rows (linked to the first branch found) ──
INSERT INTO KAL_RECON.RCN_RECON_USER
    (BANK_ID, USERNAME, FULL_NAME, EMAIL, MOBILE_NUMBER, USER_TYPE, CONTACT_RANK,
     PASSWORD_HASH, PASSWORD_SET, STATUS, APPROVED_YN, EMPLOYMENT_TYPE, CREATED_AT, CREATED_BY)
SELECT BANK_ID, 'test.branchuser1', 'Test Branch User One', 'test.branchuser1@example.com', '9876543212',
       'BRANCH_USER', 'PRIMARY', '$2a$10$dummyBcryptHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXX', 1,
       'ACTIVE', 'Y', 'INTERNAL', SYSTIMESTAMP, 'SYSTEM'
FROM KAL_RECON.RECON_BANK_MASTER
WHERE PARENT_BANK_ID IS NOT NULL AND CONTACT_RANK = 'PRIMARY' AND ROWNUM = 1;

INSERT INTO KAL_RECON.RCN_RECON_USER
    (BANK_ID, USERNAME, FULL_NAME, EMAIL, MOBILE_NUMBER, USER_TYPE, CONTACT_RANK,
     PASSWORD_HASH, PASSWORD_SET, STATUS, APPROVED_YN, EMPLOYMENT_TYPE, CREATED_AT, CREATED_BY)
SELECT BANK_ID, 'test.branchuser2', 'Test Branch User Two', 'test.branchuser2@example.com', '9876543213',
       'BRANCH_USER', 'PRIMARY', '$2a$10$dummyBcryptHashPlaceholderXXXXXXXXXXXXXXXXXXXXXXXXX', 1,
       'ACTIVE', 'Y', 'EXTERNAL', SYSTIMESTAMP, 'SYSTEM'
FROM KAL_RECON.RECON_BANK_MASTER
WHERE PARENT_BANK_ID IS NOT NULL AND CONTACT_RANK = 'PRIMARY' AND ROWNUM = 1;

COMMIT;

-- Verify:
-- SELECT USER_ID, BANK_ID, USERNAME, FULL_NAME, USER_TYPE, STATUS FROM KAL_RECON.RCN_RECON_USER WHERE USERNAME LIKE 'test.%';
