-- ============================================================
-- Fix: KAL_ADMIN "My Organization" child menu order.
-- No ORDER_BY column exists on RECON_MENU_MASTER — display order follows
-- MENU_ID (insertion order). Delete + reinsert (one-by-one, in order) to force:
--   1. Overview
--   2. Bank Branches
--   3. Bank Onboarding
--   4. My Hierarchy
--   5. Admin Status
--   6. User Status
-- ============================================================

SET DEFINE OFF;

DELETE FROM KAL_RECON.RECON_MENU_MASTER
WHERE ROLE_ID = (SELECT ROLE_ID FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE = 'KAL_ADMIN')
  AND MENU_PARENT = (
        SELECT TO_CHAR(MENU_ID) FROM KAL_RECON.RECON_MENU_MASTER
        WHERE MENU_NAME = 'My Organization'
          AND ROLE_ID = (SELECT ROLE_ID FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE = 'KAL_ADMIN')
  );

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_TYPE, MENU_NAME, MENU_URL, MENU_PARENT, SUB_MENU_FLAG, STATUS, ROLE_ID, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT 'Main', 'Overview', '/admin/my-organization/overview', TO_CHAR(MENU_ID), 'N', 'Y',
       ROLE_ID, 'SYSTEM', SYSDATE, SYSDATE
FROM KAL_RECON.RECON_MENU_MASTER
WHERE MENU_NAME = 'My Organization'
  AND ROLE_ID = (SELECT ROLE_ID FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE = 'KAL_ADMIN');

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_TYPE, MENU_NAME, MENU_URL, MENU_PARENT, SUB_MENU_FLAG, STATUS, ROLE_ID, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT 'Main', 'Bank Branches', '/admin/my-organization/bank-branches', TO_CHAR(MENU_ID), 'N', 'Y',
       ROLE_ID, 'SYSTEM', SYSDATE, SYSDATE
FROM KAL_RECON.RECON_MENU_MASTER
WHERE MENU_NAME = 'My Organization'
  AND ROLE_ID = (SELECT ROLE_ID FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE = 'KAL_ADMIN');

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_TYPE, MENU_NAME, MENU_URL, MENU_PARENT, SUB_MENU_FLAG, STATUS, ROLE_ID, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT 'Main', 'Bank Onboarding', '/admin/bank-onboarding', TO_CHAR(MENU_ID), 'N', 'Y',
       ROLE_ID, 'SYSTEM', SYSDATE, SYSDATE
FROM KAL_RECON.RECON_MENU_MASTER
WHERE MENU_NAME = 'My Organization'
  AND ROLE_ID = (SELECT ROLE_ID FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE = 'KAL_ADMIN');

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_TYPE, MENU_NAME, MENU_URL, MENU_PARENT, SUB_MENU_FLAG, STATUS, ROLE_ID, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT 'Main', 'My Hierarchy', '/admin/my-organization/hierarchy', TO_CHAR(MENU_ID), 'N', 'Y',
       ROLE_ID, 'SYSTEM', SYSDATE, SYSDATE
FROM KAL_RECON.RECON_MENU_MASTER
WHERE MENU_NAME = 'My Organization'
  AND ROLE_ID = (SELECT ROLE_ID FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE = 'KAL_ADMIN');

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_TYPE, MENU_NAME, MENU_URL, MENU_PARENT, SUB_MENU_FLAG, STATUS, ROLE_ID, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT 'Main', 'Admin Status', '/admin/my-organization/admin-status', TO_CHAR(MENU_ID), 'N', 'Y',
       ROLE_ID, 'SYSTEM', SYSDATE, SYSDATE
FROM KAL_RECON.RECON_MENU_MASTER
WHERE MENU_NAME = 'My Organization'
  AND ROLE_ID = (SELECT ROLE_ID FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE = 'KAL_ADMIN');

INSERT INTO KAL_RECON.RECON_MENU_MASTER
    (MENU_TYPE, MENU_NAME, MENU_URL, MENU_PARENT, SUB_MENU_FLAG, STATUS, ROLE_ID, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT 'Main', 'User Status', '/admin/my-organization/user-status', TO_CHAR(MENU_ID), 'N', 'Y',
       ROLE_ID, 'SYSTEM', SYSDATE, SYSDATE
FROM KAL_RECON.RECON_MENU_MASTER
WHERE MENU_NAME = 'My Organization'
  AND ROLE_ID = (SELECT ROLE_ID FROM KAL_RECON.RECON_ROLE_MASTER WHERE ROLE_CODE = 'KAL_ADMIN');

COMMIT;
