-- ============================================================
-- Migration: Auth V2 — Bank Onboarding + 3-Step Login
-- Run once on Oracle DB before starting the application
-- ============================================================

-- 1. RECON_BANK_MASTER — add new columns
ALTER TABLE KAL_RECON.RECON_BANK_MASTER ADD (
    ENABLE_MFA    NUMBER(1),
    ENABLE_OTP    NUMBER(1),
    ENABLE_HRMS   NUMBER(1),
    PRIMARY_FULL_NAME   VARCHAR2(200),
    PRIMARY_EMAIL       VARCHAR2(150),
    PRIMARY_MOBILE      VARCHAR2(20),
    SECONDARY_FULL_NAME VARCHAR2(200),
    SECONDARY_EMAIL     VARCHAR2(150),
    SECONDARY_MOBILE    VARCHAR2(20),
    BANK_ADMIN_USERNAME VARCHAR2(100),
    DEFAULT_PASSWORD    VARCHAR2(255),
    VERIFICATION_TOKEN  VARCHAR2(255),
    TOKEN_EXPIRY        TIMESTAMP
);

-- 2. BANK_TYPE column already widened in previous migration (VARCHAR2 100)
-- ALTER TABLE KAL_RECON.RECON_BANK_MASTER MODIFY BANK_TYPE VARCHAR2(100);

-- 3. RCN_RECON_USER — add CONTACT_RANK if not present (should already exist)
-- ALTER TABLE KAL_RECON.RCN_RECON_USER ADD CONTACT_RANK VARCHAR2(10);

-- 4. AUDIT_USER_DELEGATION — already exists (confirmed by user)
-- If it doesn't exist yet, create it:
/*
CREATE TABLE KAL_RECON.AUDIT_USER_DELEGATION (
    DELEGATION_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DELEGATOR_USER_ID NUMBER NOT NULL,
    DELEGATEE_USER_ID NUMBER NOT NULL,
    BANK_ID           NUMBER,
    REASON            VARCHAR2(500),
    STATUS            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    DELEGATED_AT      TIMESTAMP,
    DELEGATED_BY      VARCHAR2(100),
    RESTORED_AT       TIMESTAMP,
    RESTORED_BY       VARCHAR2(100),
    CREATED_AT        TIMESTAMP,
    CREATED_BY        VARCHAR2(100),
    UPDATED_AT        TIMESTAMP,
    UPDATED_BY        VARCHAR2(100)
);
*/

COMMIT;
