-- Restricts a Role to specific Products (e.g. a MAKER role scoped to only UPI) — new
-- junction table backing the "Products" section added to the Privileges-assign screen.
--
-- Deliberately a plain single ID column (not a composite @EmbeddedId like C_ROLE_MENU_MAP),
-- since that pattern crashed with a Hibernate PropertyAccessException on this DB.

CREATE TABLE C_ROLE_PRODUCT_MAP (
    ID          NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ROLE_ID     NUMBER(19)      NOT NULL,
    PRODUCT_ID  NUMBER(19)      NOT NULL,
    CREATED_AT  TIMESTAMP,
    CREATED_BY  VARCHAR2(100 CHAR),
    CONSTRAINT UQ_ROLE_PRODUCT UNIQUE (ROLE_ID, PRODUCT_ID),
    CONSTRAINT FK_RRPM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES RECON_ROLE_MASTER(ROLE_ID),
    CONSTRAINT FK_RRPM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES RECON_PRODUCT_MASTER(PRODUCT_ID)
);
