-- ============================================================
-- Seed: RECON_PRODUCT_MASTER — 16 products (from old frontend PRODUCTS list)
-- Run once on Oracle DB
-- ============================================================

-- Disable SQL*Plus/SQL Developer substitution variables — without this,
-- the "&" in "Dispute & Chargeback" is treated as a bind prompt.
SET DEFINE OFF;

INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('UPI', 'UPI', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('NEFT', 'NEFT', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('RTGS', 'RTGS', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('AEPS', 'AEPS', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('BBPS', 'BBPS', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('SWIFT', 'SWIFT', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('Nostro-Vostro', 'Nostro-Vostro', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('Credit Cards', 'Credit Cards (Master, Visa, Diners, RuPay, JCB)', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('Debit Card', 'Debit Card', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('Prepaid', 'Prepaid', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('Forex Card', 'Forex Card', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('NACH', 'NACH', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('CBDC', 'CBDC', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('GL Tally', 'GL Tally', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('Cash Tally', 'Cash Tally', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO KAL_RECON.RECON_PRODUCT_MASTER (PRODUCT_NAME, PRODUCT_DESC, STATUS, CREATED_AT, CREATED_BY) VALUES ('Dispute & Chargeback', 'Dispute & Chargeback', 'ACTIVE', SYSTIMESTAMP, 'SYSTEM');

COMMIT;
