-- =============================================================================
-- SYSTEM MENU CATALOG — plain INSERTs (run manually)
--
-- Same 50 rows as menu_feature_catalog.sql, written as straight INSERT statements
-- instead of a PL/SQL block so they can be run/edited one at a time.
--
-- These rows are SYSTEM METADATA, not business data:
--     BANK_ID = NULL,  PRODUCT_ID = NULL,  MENU_PROCESS_ID = NULL,  STATUS = 'ACTIVE'
--
-- They exist ONLY so Add Menu can validate that a requested menu is registered in the
-- system. They are never granted, never bank-assigned, never process-assigned, never
-- edited/deleted/approved from any screen, and can NEVER make a menu visible by themselves.
-- Add Menu VALIDATES against a catalog row and then APPENDS a separate bank/product/process
-- row — only that appended row ever goes live.
--
-- SYSTEM_MENU_CODE is the permanent identity. MENU_NAME is a display label and may be renamed
-- at any time, so no logic keys on it. Codes are explicit and hand-defined here — NEVER
-- generated from the name.
--
-- Two kinds of sub-menu:
--   * process-driven : MENU_URL NULL, PROCESS_TYPE = EXTRACTION | RECONCILIATION.
--                      Add Menu requires a process/template; the URL is derived from it.
--   * fixed-URL      : MENU_URL = the real route, PROCESS_TYPE NULL.
--                      Add Menu needs no process map; the appended row inherits this URL.
--
-- My Organization / Administration / Dashboard are NOT here — they keep their existing
-- bootstrap architecture, untouched.
--
-- Every statement is guarded by NOT EXISTS on (SYSTEM_MENU_CODE, BANK_ID IS NULL), so
-- re-running this file inserts nothing new. SET DEFINE OFF because '&' is a substitution
-- character in SQL*Plus (Dispute & Chargeback, Banks & Branches, …).
-- =============================================================================
SET DEFINE OFF;

-- ── 1. Configuration ─────────────────────────────────────────────────────────
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG', 'Master', 'Configuration', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_TPL', 'Main', 'Template Management', 'Configuration', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_TPL');

-- process-driven sub-menus (no URL; the route comes from the chosen process/template)
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_TPL_EXTR', 'Submenu', 'Define Extraction', 'Template Management', 'Configuration', 'Y', NULL, 'EXTRACTION', NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_TPL_EXTR');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_TPL_RECON', 'Submenu', 'Define Reconciliation', 'Template Management', 'Configuration', 'Y', NULL, 'RECONCILIATION', NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_TPL_RECON');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_SETUP', 'Main', 'System Setup', 'Configuration', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_SETUP');

-- fixed-URL sub-menus (the route lives on the catalog row; no process mapping needed)
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_SETUP_FILE', 'Submenu', 'File Configuration', 'System Setup', 'Configuration', 'Y', '/setup/file-config', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_SETUP_FILE');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_SETUP_RECON', 'Submenu', 'Recon Config', 'System Setup', 'Configuration', 'Y', '/setup/recon-config', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_SETUP_RECON');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_SETUP_REPORT', 'Submenu', 'Report Configuration', 'System Setup', 'Configuration', 'Y', '/setup/report-config', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_SETUP_REPORT');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_SETUP_FTP', 'Submenu', 'FTP Configuration', 'System Setup', 'Configuration', 'Y', '/setup/ftp-config', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_SETUP_FTP');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_SETUP_FORCE', 'Submenu', 'Force Match Config', 'System Setup', 'Configuration', 'Y', '/setup/force-match', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_SETUP_FORCE');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_SETUP_TEMPLATE', 'Submenu', 'Template Config', 'System Setup', 'Configuration', 'Y', '/setup/template-config', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_SETUP_TEMPLATE');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'CFG_SETUP_PROCDEF', 'Submenu', 'Process Definition', 'System Setup', 'Configuration', 'Y', '/setup/process-definition', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'CFG_SETUP_PROCDEF');

-- ── 2. Process ───────────────────────────────────────────────────────────────
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'PROC', 'Master', 'Process', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'PROC');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'PROC_TXN', 'Main', 'Transaction Processing', 'Process', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'PROC_TXN');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'PROC_TXN_EXTR_SEARCH', 'Submenu', 'Extraction Transaction Search', 'Transaction Processing', 'Process', 'Y', '/process/extraction-search', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'PROC_TXN_EXTR_SEARCH');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'PROC_TXN_BULK_MATCH', 'Submenu', 'Bulk Process Match', 'Transaction Processing', 'Process', 'Y', '/process/bulk-match', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'PROC_TXN_BULK_MATCH');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'PROC_TXN_FILE_UPLOAD', 'Submenu', 'File Upload', 'Transaction Processing', 'Process', 'Y', '/process/file-upload', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'PROC_TXN_FILE_UPLOAD');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'PROC_TXN_SPLIT', 'Submenu', 'Split Transaction', 'Transaction Processing', 'Process', 'Y', '/process/split-transaction', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'PROC_TXN_SPLIT');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'PROC_TXN_RECON_SEARCH', 'Submenu', 'Recon Transaction Search', 'Transaction Processing', 'Process', 'Y', '/process/recon-search', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'PROC_TXN_RECON_SEARCH');

-- ── 3. Extraction (process-driven) ───────────────────────────────────────────
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'EXTR', 'Master', 'Extraction', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'EXTR');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'EXTR_PROC', 'Main', 'Extraction Processing', 'Extraction', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'EXTR_PROC');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'EXTR_PROC_FILE', 'Submenu', 'File Processing', 'Extraction Processing', 'Extraction', 'Y', NULL, 'EXTRACTION', NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'EXTR_PROC_FILE');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'EXTR_PROC_DATA', 'Submenu', 'Data Extraction', 'Extraction Processing', 'Extraction', 'Y', NULL, 'EXTRACTION', NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'EXTR_PROC_DATA');

-- ── 4. Reconciliation ────────────────────────────────────────────────────────
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON', 'Master', 'Reconciliation', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON_PROC', 'Main', 'Reconciliation Processing', 'Reconciliation', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON_PROC');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON_PROC_AUTO', 'Submenu', 'Auto Reconciliation', 'Reconciliation Processing', 'Reconciliation', 'Y', NULL, 'RECONCILIATION', NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON_PROC_AUTO');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON_PROC_MANUAL', 'Submenu', 'Manual Reconciliation', 'Reconciliation Processing', 'Reconciliation', 'Y', NULL, 'RECONCILIATION', NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON_PROC_MANUAL');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON_PROC_STATUS', 'Submenu', 'Reconciliation Status', 'Reconciliation Processing', 'Reconciliation', 'Y', '/reconciliation/status', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON_PROC_STATUS');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON_SETUP', 'Main', 'Reconciliation Setup', 'Reconciliation', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON_SETUP');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON_SETUP_TEMPLATE', 'Submenu', 'Add New Template', 'Reconciliation Setup', 'Reconciliation', 'Y', '/new-config/add-template', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON_SETUP_TEMPLATE');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON_SETUP_RULE', 'Submenu', 'Define Reconciliation Rule', 'Reconciliation Setup', 'Reconciliation', 'Y', '/new-config/reconciliation', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON_SETUP_RULE');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RECON_SETUP_OPS', 'Submenu', 'Reconciliation Ops Center', 'Reconciliation Setup', 'Reconciliation', 'Y', '/new-config/ops-center', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RECON_SETUP_OPS');

-- ── 5. Reports ───────────────────────────────────────────────────────────────
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RPT', 'Master', 'Reports', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RPT');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RPT_MAIN', 'Main', 'Reporting', 'Reports', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RPT_MAIN');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RPT_GENERATE', 'Submenu', 'Generate Report', 'Reporting', 'Reports', 'Y', '/reports/generate', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RPT_GENERATE');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RPT_TTUM', 'Submenu', 'TTUM Report', 'Reporting', 'Reports', 'Y', '/reports/ttum', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RPT_TTUM');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RPT_RECON', 'Submenu', 'Reconciliation Report', 'Reporting', 'Reports', 'Y', '/reports/reconciliation', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RPT_RECON');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'RPT_JOB_DETAILS', 'Submenu', 'Job Details', 'Reporting', 'Reports', 'Y', '/reports/extraction-details', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'RPT_JOB_DETAILS');

-- ── 6. Dispute Management ────────────────────────────────────────────────────
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'DSP', 'Master', 'Dispute Management', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'DSP');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'DSP_MAIN', 'Main', 'Dispute Handling', 'Dispute Management', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'DSP_MAIN');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'DSP_DASHBOARD', 'Submenu', 'Dispute Dashboard', 'Dispute Handling', 'Dispute Management', 'Y', '/dispute/dashboard', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'DSP_DASHBOARD');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'DSP_ACTION_CENTER', 'Submenu', 'Dispute Action Center', 'Dispute Handling', 'Dispute Management', 'Y', '/dispute/action-center', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'DSP_ACTION_CENTER');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'DSP_MAKER_UPLOAD', 'Submenu', 'Maker Upload', 'Dispute Handling', 'Dispute Management', 'Y', '/dispute/maker-upload', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'DSP_MAKER_UPLOAD');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'DSP_CHECKER_APPROVAL', 'Submenu', 'Checker Approval', 'Dispute Handling', 'Dispute Management', 'Y', '/dispute/checker-approval', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'DSP_CHECKER_APPROVAL');

-- ── 7. UPI Reconciliation ────────────────────────────────────────────────────
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'UPI', 'Master', 'UPI Reconciliation', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'UPI');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'UPI_MAIN', 'Main', 'UPI Recon', 'UPI Reconciliation', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'UPI_MAIN');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'UPI_DASHBOARD', 'Submenu', 'UPI Recon Dashboard', 'UPI Recon', 'UPI Reconciliation', 'Y', '/upi-recon/dashboard', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'UPI_DASHBOARD');

-- ── 8. NEFT Reconciliation ───────────────────────────────────────────────────
INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'NEFT', 'Master', 'NEFT Reconciliation', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'NEFT');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'NEFT_MAIN', 'Main', 'NEFT Recon', 'NEFT Reconciliation', NULL, 'N', NULL, NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'NEFT_MAIN');

INSERT INTO RECON_MENU_MASTER (MENU_ID, SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MASTER_MENU_PARENT, SUB_MENU_FLAG, MENU_URL, PROCESS_TYPE, MENU_PROCESS_ID, BANK_ID, PRODUCT_ID, STATUS, IS_PORTAL_TWIN, CREATED_BY, CREATED_DATE, INSERT_DATE)
SELECT SEQ_MENU.NEXTVAL, 'NEFT_CYCLE', 'Submenu', 'NEFT Cycle Management', 'NEFT Recon', 'NEFT Reconciliation', 'Y', '/neft-recon/dashboard', NULL, NULL, NULL, NULL, 'ACTIVE', 'N', 'CATALOG', SYSDATE, SYSDATE FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM RECON_MENU_MASTER WHERE BANK_ID IS NULL AND SYSTEM_MENU_CODE = 'NEFT_CYCLE');

COMMIT;

-- ── Verify ───────────────────────────────────────────────────────────────────
SET PAGESIZE 200 LINESIZE 160;
COL SYSTEM_MENU_CODE FORMAT A22
COL MENU_NAME        FORMAT A30
COL MENU_PARENT      FORMAT A26
COL MENU_URL         FORMAT A30
COL PROCESS_TYPE     FORMAT A15
SELECT SYSTEM_MENU_CODE, MENU_TYPE, MENU_NAME, MENU_PARENT, MENU_URL, PROCESS_TYPE
  FROM RECON_MENU_MASTER
 WHERE BANK_ID IS NULL AND CREATED_BY = 'CATALOG'
 ORDER BY DECODE(MENU_TYPE, 'Master', 1, 'Main', 2, 3), SYSTEM_MENU_CODE;

-- Expect 8 Master + 10 Main + 32 Submenu = 50
SELECT MENU_TYPE, COUNT(*) CNT FROM RECON_MENU_MASTER
 WHERE BANK_ID IS NULL AND CREATED_BY = 'CATALOG' GROUP BY MENU_TYPE;

-- Integrity: a catalog row must never carry a bank / product / process. Expect 0.
SELECT COUNT(*) AS CATALOG_ROWS_WITH_SCOPE FROM RECON_MENU_MASTER
 WHERE CREATED_BY = 'CATALOG'
   AND (BANK_ID IS NOT NULL OR PRODUCT_ID IS NOT NULL OR MENU_PROCESS_ID IS NOT NULL);
