package com.jpb.reconciliation.reconciliation.enums;

/**
 * StandardRole — role CATEGORY template.
 *
 * IMPORTANT CHANGE FROM PREVIOUS VERSION:
 * ─────────────────────────────────────────
 * Previously this enum was also the source of the unique role code stored in
 * the database.  That meant only one MAKER, one CHECKER, etc. could ever exist.
 *
 * Now the enum defines the BASE CODE for each category (used only as a
 * human-readable reference / display label).  The actual unique 4-digit code
 * stored in REC_ROLES_TEST.ROLE_CODE is generated by the DB sequence
 * ROLE_CODE_SEQ (standard) or ROLE_CODE_CUSTOM_SEQ (OTHER/custom).
 *
 * Examples after the change:
 *   MAKER_UPI   → roleCode "1008"  (sequence)
 *   MAKER_NEFT  → roleCode "1009"  (sequence)
 *   CHECKER_UPI → roleCode "1010"  (sequence)
 *   MY_CUSTOM   → roleCode "9001"  (custom sequence)
 *
 * baseCode is still useful for:
 *   • UI display ("this is a MAKER-family role, base 1001")
 *   • Grouping / filtering roles by category in reports
 *   • Backward-compat mapping when reading legacy data
 */
public enum StandardRole {

    MAKER(1001),
    CHECKER(1002),
    WORKER(1003),
    AUDITOR(1004),
    IT_OPS(1005),
    SUPERVISOR(1006),
    RCC_CXO(1007),
    OTHER(9000);          // custom roles — codes start at 9001 via separate seq

    // ── base code: category reference, NOT the DB unique code anymore ────────
    private final int baseCode;

    StandardRole(int baseCode) {
        this.baseCode = baseCode;
    }

    /** Category base code — for display/grouping only, not stored as roleCode. */
    public int getBaseCode() {
        return baseCode;
    }

    /**
     * Resolve a StandardRole from a role name string (case-insensitive).
     * Returns OTHER if no match — never returns null.
     *
     * Examples:
     *   "MAKER"       → MAKER
     *   "maker"       → MAKER
     *   "MAKER_UPI"   → OTHER  (custom name, not a bare enum value)
     *   "MY_THING"    → OTHER
     */
    public static StandardRole fromRoleName(String roleName) {
        if (roleName == null ||  roleName.trim().isEmpty()) {
            return OTHER;
        }
        for (StandardRole role : values()) {
            if (role.name().equalsIgnoreCase(roleName.trim())) {
                return role;
            }
        }
        return OTHER;
    }

    /**
     * Returns true when this role category is "standard" (not custom/OTHER).
     * Standard-family roles use ROLE_CODE_SEQ.
     * OTHER/custom roles use ROLE_CODE_CUSTOM_SEQ.
     */
    public boolean isStandard() {
        return this != OTHER;
    }

    /**
     * Legacy helper — kept for backward compatibility with any existing code
     * that calls getCodeByRoleName().
     *
     * @deprecated Use {@link #fromRoleName(String)} and {@link #getBaseCode()}
     *             instead.  This method now returns the BASE code, not a unique
     *             DB role code.
     */
    @Deprecated
    public static Integer getCodeByRoleName(String roleName) {
        StandardRole resolved = fromRoleName(roleName);
        return resolved.getBaseCode();
    }
}